### PR TITLE
Bug fixes and Code Refactoring

### PR DESCRIPTION
**Pull request by Advik-B**
The base code refactoring is provided by Sourcery https://github.com/Advik-B/librespot-python/pull/1

Hotfix 1: Fix SSL warning/error https://github.com/kokarare1212/librespot-python/commit/17a4f4626b599725df0a4483ff993978e5aa75f5 https://github.com/kokarare1212/librespot-python/commit/784f0ff93f7d2cf8edfdb0a389a2ca2571d249fe

Hotfix 2: Fixing a parsing error https://github.com/jsavargas/zspotify/issues/149#issuecomment-1773865540

### CODE REVIEW

**Comment by kokarare1212** [comment]
The new method of obtaining expiration dates has already been implemented in [this commit](https://github.com/kokarare1212/librespot-python/commit/f97b6b2fe1471373dd643f6ecbe6555f002704e1).
It is also dangerous to disable SSL verification.

**Comment by Advik-B** [comment]
> The new method of obtaining expiration dates has already been implemented in [this commit](https://github.com/kokarare1212/librespot-python/commit/f97b6b2fe1471373dd643f6ecbe6555f002704e1). It is also dangerous to disable SSL verification.

Do you want me to re-enable SSL?

**Comment by kokarare1212** [comment]
Perhaps what this PR needs is a reference tag, and Restyled.io has already done that.

**Comment by Advik-B** [comment]
> Perhaps what this PR needs is a reference tag, and Restyled.io has already done that.

Alright, ill re-enable ssl, what else?

**Comment by kokarare1212** [comment]
Anyway, this PR is no longer needed as a temporary solution has been implemented.
#241

**Comment by Advik-B** [comment]
Fineee 😞

**Pull request closed without merging**
